// Generated by https://quicktype.io

import { KnownFor } from "./listado.interface";

export interface PeopleDetailResponse {
    adult:                boolean;
    also_known_as:        string[];
    biography:            string;
    birthday:             string;
    deathday:             null;
    gender:               number;
    homepage:             null;
    id:                   number;
    imdb_id:              string;
    known_for_department: string;
    name:                 string;
    place_of_birth:       string;
    popularity:           number;
    profile_path:         string;
}
export interface DialogData{
    peopleInfo: PeopleDetailResponse;
    filmsList: KnownFor[];
}